services:
  rocom-push:
    image: ghcr.io/jayegt002/rocom-webhook-push:latest
    container_name: rocom-push
    restart: unless-stopped
    volumes:
      - ./settings.yaml:/app/settings.yaml:ro
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
