# 推送配置

# WeGmae API配置
wegame_api_key: "sk-placeholder"
base_url: "https://wegame.shallow.ink"

# 推送渠道开关（true 开启，false 关闭）
bark: true
feishu: false
serverchan: false

# Bark配置
bark_key: "placeholder"
bark_server: "https://api.day.app"
bark_icon: "https://raw.githubusercontent.com/JayeGT002/rocom-push/main/logo.png"

# 飞书配置
feishu_hook: "placeholder"

# Serverchan配置
# 不兼容Server酱Tubro，请从Server酱³官网 https://sc3.ft07.com 获取相关配置。
serverchan_uid: "placeholder"
serverchan_key: "placeholder"
