# WeGmae API配置
wegame_api_key: ""
base_url: "https://wegame.shallow.ink"

# 推送渠道开关（true 开启，false 关闭）
bark: true
feishu: false
serverchan: false

# Bark配置
bark_key: ""
bark_server: "https://api.day.app"
bark_icon: ""

# 飞书配置
feishu_hook: ""

# Serverchan配置
serverchan_uid: ""
serverchan_key: ""
